import { DEFAULT_PEAK_DETECTION, type SpectrumDataset } from '../../types/project'

export const RUNNER_DIRECTORY = '/tmp/spectraliser_scripts'

/** Script inputs only; display metadata never reaches the runner. */
export interface RunnerSampleMetadata {
  spectrumType: string
  units: { x: string; y: string }
  pipeline: SpectrumDataset['pipeline']
  peakDetection: NonNullable<SpectrumDataset['peakDetection']>
}

export function runnerMetadata(dataset: SpectrumDataset): RunnerSampleMetadata {
  return {
    spectrumType: dataset.spectrumType,
    units: { x: dataset.units.x, y: dataset.units.y },
    pipeline: dataset.pipeline,
    peakDetection: dataset.peakDetection ?? { ...DEFAULT_PEAK_DETECTION },
  }
}

/** Modules the generated runner imports; main.py and samples.json are standalone-only. */
export function runnerScriptFiles(files: Record<string, string>): Record<string, string> {
  return Object.fromEntries(Object.entries(files).filter(([name]) => name.endsWith('.py') && name !== 'main.py'))
}

/**
 * Generates the entry script for one triggered execution. It lists only the
 * changed samples and calls the editable processing/IR modules directly instead
 * of main.py, so unchanged samples and samples.json are never touched.
 */
export function buildRunScript(sampleIds: string[]): string {
  return [
    '# Generated by Spectraliser for this execution only; main.py is not run.',
    'import sys',
    `if ${JSON.stringify(RUNNER_DIRECTORY)} not in sys.path:`,
    `    sys.path.insert(0, ${JSON.stringify(RUNNER_DIRECTORY)})`,
    'from processing import process_spectrum',
    'from ir_assignments import assign_ir_peaks',
    'from selective_run import run_samples',
    '',
    `CHANGED_SAMPLE_IDS = ${JSON.stringify(sampleIds)}`,
    '',
    'run_results = run_samples(CHANGED_SAMPLE_IDS, runner_samples, process_spectrum, assign_ir_peaks)',
    '',
  ].join('\n')
}
